### ISSUE TITLE
API naming

### ISSUE THREAD

**Issue by p1nox** [axiomzen/express-interceptor#4]
I'm not convinced about exposing the method named as "initerceptPredicate". What about if we change the api a little?

* From:

```javascript
var interceptor = require('express-interceptor');
app.use(interceptor(function(req,res){
  return {
    initerceptPredicate: function(){

    },
    send: function(body, done) {

    },
    afterSend: function(oldBody, newBody) {

    }
  };
}));
```

* To:

```javascript
var interceptor = require('express-interceptor');
app.use(interceptor(function(req,res){
  return {
    isInterceptable: function(){

    },
    intercept: function(body, send) {

    },
    afterSend: function(oldBody, newBody) {

    }
  };
}));
```

**Comment by flockonus** [comment]
Oh yeah, `initerceptPredicate` was a typo :astonished: 
I'm just afraid `send` could be a bit hard to identify as a callback, altho I'm not sure exactly how to solve that. It's just a suggestion of a name anyway, since it's a param for a function. Maybe we could have `send` but then it could take just 1 param which is the string, since right now if the user send a callback we cannot do anything with it anyway (no way to pass down the stack)

**Comment by p1nox** [comment]
Ok, so we can change the name of the predicate to `isInterceptable `. And for the send function, I think it is specific enough because it is a verb, hence is an action, and also we could define a check phase internally to throw an error in case a function is passed into the method `send(function(){})`, something like "You shouldn't be passing a function as a response.". We could be oppinionated and say that our send method it will receive params in order (error, response), because it is the expected standard for callbacks.

**Comment by flockonus** [comment]
Took all suggestions, except the send callback packing the error because it's a tricky one! We could actually take it, but the problem is that there is no way to handle that error, afaik can't call `next(err)`, so worst case the user should send an empty response with `done()` and set the appropriate status code to `res`
