### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by p1nox** [axiomzen/express-interceptor#8]
* Link to LICENSE file.
* Add a section with "use cases".

**Comment by dgipps** [comment]
A few suggestions around improving the README:

- Raison d'etre section isn't clear
   - "Born out of the need for a reliable, customized and maintenable (typo here - maintainable) middleware we need for Sesame CMS." only really says that this is a middleware. Better to say something like "While working on Sesame CMS we found the need for a reliable, customizable, and maintainable middleware to do..."
   - The two listed use cases aren't really use cases but rather a general overview of what express-interceptor does. It would be better to make uses cases more like "Store statistics about responses" or "Modify every response with an html body".

- API section could be expanded
   - At least one of the examples should be on the README
   - `done(err, string) param[1] will become the new response` would be more clear as `done(err, newBody)`
   - A lot of the examples have interceptPredicate just return true so I was a little confused at first. I would suggest adding some wording to suggest that interceptPredicate can review `req` and `res` to create a condition for whether the response should be intercepted. 

- Technicalities are unclear to me (possibly because I am not a Node/Express expert but I think there needs to be more clarity)
   - "allow setting and modifying of headers until the moment there is a write to the socket, this will submit headers." What does it mean a write to the socket, and how does this affect me as a user of this library? 
   - In general, if these aren't too important to use of the library, they should probably be moved to a separate link off of the main README

**Comment by paigepaquette** [comment]
+1 to all of this, particularly: 
>The two listed use cases aren't really use cases but rather a general overview of what express-interceptor does. It would be better to make uses cases more like "Store statistics about responses" or "Modify every response with an html body".
